steps:
  - id: test
    name: golang:latest
    entrypoint: bash
    args:
      - '-c'
      - |
        go test ./... -v
  - id: deploy-api
    name: gcr.io/cloud-builders/gcloud
    waitFor:
      - test
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud run deploy salmonping --source . \
          --allow-unauthenticated \
          --concurrency 16 \
          --cpu 1 \
          --max-instances 5 \
          --memory 128Mi \
          --min-instances 0 \
          --region=asia-southeast1 \
          --service-account salmonping@salmonping.iam.gserviceaccount.com \
          --set-secrets API_KEY=salmonping_API_KEY:latest \
          --set-secrets DATABASE_URL=salmonping_DATABASE_URL:latest \
          --set-secrets GOFOOD_NOTIFICATION_SECRET_KEY=salmonping_GOFOOD_NOTIFICATION_SECRET_KEY:latest \
          --set-secrets TELEGRAM_BOT_TOKEN=salmonping_TELEGRAM_BOT_TOKEN:latest \
          --set-secrets TELEGRAM_CHAT_ID=salmonping_TELEGRAM_CHAT_ID:latest \
          --tag=main \
          --timeout 60s \
          --update-labels service=salmonping
options:
  logging: CLOUD_LOGGING_ONLY
