// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OnlineListing struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Name      string             `json:"name"`
	Platform  string             `json:"platform"`
	Url       string             `json:"url"`
}

type SalmonPing struct {
	ID              pgtype.UUID        `json:"id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Status          string             `json:"status"`
	OnlineListingID pgtype.UUID        `json:"online_listing_id"`
}

type Schedule struct {
	ID              pgtype.UUID `json:"id"`
	OnlineListingID pgtype.UUID `json:"online_listing_id"`
	DayOfWeek       int32       `json:"day_of_week"`
	OpeningTime     pgtype.Time `json:"opening_time"`
	ClosingTime     pgtype.Time `json:"closing_time"`
}
