// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OnlineListing struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Name      string
	Platform  string
	Url       string
}

type SalmonPing struct {
	ID              pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	Status          string
	OnlineListingID pgtype.UUID
}

type Schedule struct {
	ID              pgtype.UUID
	OnlineListingID pgtype.UUID
	DayOfWeek       int32
	OpeningTime     pgtype.Time
	ClosingTime     pgtype.Time
}
